"""Adding permission to teachers

Revision ID: 49a80e7e479f
Revises: 8aabfb2aed73
Create Date: 2019-09-12 00:12:04.840609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a80e7e479f'
down_revision = '29b9e3d13be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_users', sa.Column('can_create', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_users', 'can_create')
    # ### end Alembic commands ###
