"""Adding permission to teachers

Revision ID: 8aabfb2aed73
Revises: 84c4430cfd16
Create Date: 2019-09-11 20:59:06.947776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aabfb2aed73'
down_revision = '84c4430cfd16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_users', sa.Column('can_delete', sa.Boolean(), nullable=True))
    op.add_column('application_users', sa.Column('can_update', sa.Boolean(), nullable=True))
    op.add_column('application_users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_users', 'is_admin')
    op.drop_column('application_users', 'can_update')
    op.drop_column('application_users', 'can_delete')
    # ### end Alembic commands ###
